get:
  summary: List
  operationId: listProduct
  description: List all products
  tags:
  - Products
  parameters:
    - $ref: "../../parameters/query/limit.yaml"
    - $ref: "../../parameters/query/last_key.yaml"
    - $ref: "../../parameters/query/name.yaml"
  responses:
    200:
      description: A paged array of products
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: "../../schemas/Product.yaml"
              has_more:
                type: boolean
              last_key:
                type: string
                format: uuid      
    default:
      $ref: "../../responses/UnexpectedError.yaml"
post:
  summary: Create
  operationId: createProduct
  description: Create a product
  tags:
  - Products
  responses:
    '201':
        $ref : "../../responses/NullResponse.yaml"
    default:
        $ref : "../../responses/UnexpectedError.yaml"

