type: object
required:
  - name
properties:
  id:
    type: string
    format: uuid
  name:
    type: string
  external_reference:
    type: string
    nullable: true
    description: The reference given by the payment provider
  tax_type:
    type: string
    example: 'digital_goods'
    nullable: true
    description: "The tax type for the product <strong>Since 1.1</strong>"
  prices:
    type: array
    items:
       $ref: "./Price.yaml"