type: object
required:
  - name
properties:
  id:
    type: string
    format: uuid
  name:
    type: string
  external_reference:
    type: string
    nullable: true
    description: The reference given by the payment provider
  tax_type:
    $ref: "./TaxType.yaml"   