openapi: "3.0.0"
info:
  version: 1.1.0
  title: BillaBear
  description: The REST API provided by BillaBear
  license:
    name: FCL
  contact:
    name: API Support
    url: http://www.billabear.com/support
    email: support@billabear.com
servers:
  - url: https://{customerId}.billabear.cloud/api/v1
    variables:
      customerId:
        default: demo
        description: Customer ID assigned by the service provider
security:
  - ApiKeyAuth: []        
tags:
  - name: Billing
paths:
  /customer:
    $ref: "./resources/customers/customers.yaml"
  /customer/{customerId}:
    $ref: "./resources/customers/customer.yaml"
  /customer/{customerId}/voucher:
    $ref: "./resources/customers/applyVoucher.yaml"
  /customer/{customerId}/costs:
    $ref: "./resources/customers/costs.yaml"
  /customer/{customerId}/manage-link:
    $ref: "./resources/customers/portal.yaml"
  /customer/{customerId}/disable:
    $ref: "./resources/customers/disable.yaml"
  /customer/{customerId}/enable:
    $ref: "./resources/customers/enable.yaml"
  /customer/{customerId}/limits:
    $ref: "./resources/customers/limits.yaml"
  /customer/{customerId}/refund:
    $ref: "./resources/customers/refund.yaml"
  /customer/{customerId}/payment:
    $ref: "./resources/customers/payment.yaml"  
  /customer/{customerId}/uasge-limit:
    $ref: "./resources/customers/usageLimits.yaml"  
  /customer/{customerId}/uasge-limit/{limitId}:
    $ref: "./resources/customers/deleteUsageLimit.yaml"  
  /customer/{customerId}/invoices:
    $ref: "./resources/customers/invoices.yaml"  
  /customer/{customerId}/payment-methods/frontend-payment-token:
    $ref: "./resources/paymentDetails/frontendPaymentDetails.yaml"
  /customer/{customerId}/payment-methods/{paymentDetailsId}:
    $ref: "./resources/paymentDetails/paymentDetailCustomer.yaml"    
  /payment-methods/{paymentDetailsId}:
    $ref: "./resources/paymentDetails/paymentDetail.yaml"    
  /customer/{customerId}/payment-methods:
    $ref: "./resources/paymentDetails/paymentDetails.yaml"  
  /customer/{customerId}/payment-methods/{paymentDetailsId}/default:
    $ref: "./resources/paymentDetails/makeDefaultCustomer.yaml"
  /payment-methods/{paymentDetailsId}/default:
    $ref: "./resources/paymentDetails/makeDefault.yaml"
  /customer/{customerId}/subscription/start:
    $ref: "./resources/subscriptions/customerStart.yaml"
  /customer/{customerId}/subscription/trial:
    $ref: "./resources/subscriptions/customerStartTrial.yaml"
  /customer/{customerId}/subscription:
    $ref: "./resources/subscriptions/customerSubscriptions.yaml"
  /customer/{customerId}/subscription/active:
    $ref: "./resources/subscriptions/customerSubscriptionsActive.yaml"
  /payment:
    $ref: "./resources/payments/list.yaml"  
  /payment/{paymentId}/refund:
    $ref: "./resources/payments/refund.yaml"  
  /refund:
    $ref: "./resources/refunds/list.yaml"  
  /refund/{refundId}:
    $ref: "./resources/refunds/refund.yaml"  
  /product:
    $ref: "./resources/products/products.yaml"
  /product/{productId}:
    $ref: "./resources/products/product.yaml"
  /product/{productId}/price:
    $ref: "./resources/products/prices.yaml"
  /subscription:
    $ref: "./resources/subscriptions/subscriptions.yaml"  
  /subscription/plans:
    $ref: "./resources/subscriptions/plans.yaml"  
  /subscription/{subscriptionId}:
    $ref: "./resources/subscriptions/subscription.yaml"  
  /subscription/{subscriptionId}/seats/add:
    $ref: "./resources/subscriptions/seatsAdd.yaml"  
  /subscription/{subscriptionId}/seats/remove:
    $ref: "./resources/subscriptions/seatsRemove.yaml"  
  /subscription/{subscriptionId}/cancel:
    $ref: "./resources/subscriptions/cancel.yaml"  
  /subscription/{subscriptionId}/extend:
    $ref: "./resources/subscriptions/extend.yaml"  
  /subscription/{subscriptionId}/plan:
    $ref: "./resources/subscriptions/subscriptionPlan.yaml"  
  /subscription/{subscriptionId}/price:
    $ref: "./resources/subscriptions/changePrice.yaml"  
  /checkout:
    $ref: "./resources/checkout/create.yaml"
  /invoice/{invoiceId}/charge:
    $ref: "./resources/invoices/charge.yaml"  
  /invoice/{invoiceId}/download:
    $ref: "./resources/invoices/download.yaml"  
  /receipt/{receiptId}/download:
    $ref: "./resources/receipts/download.yaml"  
  /events:
    $ref: "./resources/events/events.yaml"
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
  parameters:
    $ref: "./parameters/_index.yaml"
  schemas:
    $ref: "./schemas/_index.yaml"
  responses:
    $ref: "./responses/_index.yaml"