openapi: "3.0.0"
info:
  version: 1.0.0
  title: BillaBear
  description: The REST API provided by BillaBear
  license:
    name: BUSL-1.1
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com
servers:
  - url: http://petstore.swagger.io/v1
tags:
  - name: Billing
paths:
  /customer:
    $ref: "./resources/customers/customers.yaml"
  /customer/{customerId}:
    $ref: "./resources/customers/customer.yaml"
  /product:
    $ref: "./resources/products/products.yaml"
  /product/{productId}:
    $ref: "./resources/products/product.yaml"
  /product/{productId}/price:
    $ref: "./resources/products/prices.yaml"
components:
  parameters:
    $ref: "./parameters/_index.yaml"
  schemas:
    $ref: "./schemas/_index.yaml"
  responses:
    $ref: "./responses/_index.yaml"